## Model generation:
#
# Typescript:
# java -jar ../openapi-generator-cli.jar generate -i ../../docs/source/_static/openapi/schemas.yml -g typescript-angular -o src --global-property models
#
# Python (service):
# call in service root directory
# java -Dmodels -DsupportingFiles=util.py,base_model.py,typing_utils.py,__init__.py -jar ../openapi-generator-cli.jar generate -i ../../docs/source/_static/openapi/schemas.yml -g python-flask -o . --additional-properties=packageName='grader_service.api' ; rm -r grader_service/api/test grader_service/api/controllers grader_service/api/openapi

#
# Python (labextension):
# call in labextension root directory
# java -Dmodels -DsupportingFiles=util.py,base_model.py,typing_utils.py -jar ../openapi-generator-cli.jar generate -i ../../docs/source/_static/openapi/schemas.yml -g python-flask -o . --additional-properties=packageName='grader_labextension.api' ; rm -r grader_labextension/api/test grader_labextension/api/controllers grader_labextension/api/openapi .openapi-generator/


openapi: '3.0.2'
info:
  title: Grader Extension API Schemas
  version: '0.1'

paths:
  /:
    get:
      responses:
        200:
          description: OK

###### Data type definitions
components:
  schemas:
    User:
      type: object
      required: [ "id", "username", "display_name" ]
      properties:
        id:
          type: integer
          format: int64
          example: 1
        name:
          type: string
          example: "Baz Bar"
        display_name:
          type: string
          example: "Baz Bar"
      example:
        id: 1
        name: "Baz Bar"
        display_name: "Baz Bar"
    LectureDetailDto:
      type: object
      required: [ "id", "name", "code", "complete" ]
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
          example: "Informationsvisualisierung"
        code:
          type: string
          example: "ivs21"
        complete:
          type: boolean
          default: false
      example:
        name: "Informationsvisualisierung"
        code: "ivs21"
        complete: false
    LectureCreateDto:
      type: object
      required: ["name", "code", "complete"]
      properties:
        name:
          type: string
          example: "Informationsvisualisierung"
        code:
          type: string
          example: "ivs21"
        complete:
          type: boolean
          default: false
    LectureUpdateDto:
      type: object
      required: [ "name", "complete" ]
      properties:
        name:
          type: string
          example: "Informationsvisualisierung"
        complete:
          type: boolean
          default: false
      example:
        id: 1
        name: "Informationsvisualisierung"
        complete: false
    LectureListItemDto:
      type: object
      required: [ "id", "name", "code", "complete", "assignment_count" ]
      properties:
        id:
          type: integer
          format: int64
          example: 1
        name:
          type: string
          example: "Informationsvisualisierung"
        code:
          type: string
          example: "ivs21"
        complete:
          type: boolean
          default: false
        assignment_count:
          type: integer
          format: int64
        student_count:
          type: integer
          format: int64
    LectureListDto:
      type: object
      required: [ "lectures", "page", "per_page", "total_items", "total_pages" ]
      properties:
        lectures:
          type: array
          items:
            $ref: "#/components/schemas/LectureListItemDto"
        page:
          type: integer
          format: int64
          description: Current page number (1-based)
          example: 1
        per_page:
          type: integer
          format: int64
          description: Number of lectures per page
          example: 20
        total_items:
          type: integer
          format: int64
          description: Total number of lectures matching the filters
          example: 15
        total_pages:
          type: integer
          format: int64
          description: Total number of pages
          example: 1
        total_items_unfiltered:
          type: integer
          format: int64
          description: Total number of pages (unfiltered results)
          example: 15
      example:
        lectures:
          - id: 1
            name: "Informationsvisualisierung"
            code: "ivs21"
            complete: false
            assignment_count: 3
        page: 1
        per_page: 20
        total_items: 1
        total_pages: 1
    AssignmentDetailBaseDto:
      type: object
      required: [ "name", "points" ]
      properties:
        name:
          type: string
          example: "assignment_1"
        points:
          type: number
          format: float
        submissions:
          type: array
          items:
            $ref: "#/components/schemas/SubmissionListItemDto"
    AssignmentDetailStudentDto:
      allOf:
        - $ref: "#/components/schemas/AssignmentDetailBaseDto"
        - type: object
          required: [ "deadline" ]
          properties:
            deadline:
              type: string
              format: date-time
    AssignmentDetailInstructorDto:
      allOf:
        - $ref: "#/components/schemas/AssignmentDetailBaseDto"
        - type: object
          required: [ "status", "grading_method" ]
          properties:
            status:
              $ref: "#/components/schemas/AssignmentStatus"
            grading_method:
              $ref: "#/components/schemas/GradingMethod"
    AssignmentCreateDto:
      type: object
      required: [ "name" ]
      properties:
        name:
          type: string
          example: "assignment_1"
        settings:
          $ref: "#/components/schemas/AssignmentSettings"
    AssignmentUpdateDto:
      type: object
      required: [ "id", "name" ]
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
          example: "assignment_1"
        settings:
          $ref: "#/components/schemas/AssignmentSettings"
    AssignmentListItemBaseDto:
      type: object
      required: [ "id", "name", "deadline", "submission_count" ]
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
          example: "assignment_1"
        deadline:
          type: string
          format: date-time
        submission_count: # instructor view: number of all submissions; student view: number of remaining submissions
          type: integer
          format: int64
    AssignmentListItemInstructorDto:
      allOf:
        - $ref: "#/components/schemas/AssignmentListItemBaseDto"
        - type: object
          required: [ "status", "points", "grading_method" ]
          properties:
            status:
              $ref: "#/components/schemas/AssignmentStatus"
            points:
              type: number
              format: float
            grading_method:
              $ref: "#/components/schemas/GradingMethod"
    AssignmentListItemUpcomingDto:
      type: object
      required: [ "name", "lecture_code", "lecture_name", "deadline", "late_submissions_allowed" ]
      properties:
        name:
          type: string
          example: "assignment_1"
        lecture_code:
          type: string
          example: "ivs21"
        lecture_name:
          type: string
          example: "Informationsvisualisierung"
        deadline:
          type: string
          format: date-time
        late_submissions_allowed:
          type: boolean
          default: false
    AssignmentSettings:
      type: object
      required: [ "grading_method" ]
      properties:
        deadline:
          type: string
          format: date-time
        max_submissions:
          type: integer
          format: int64
        allowed_files:
          type: array
          items:
            type: string
          default: []
        late_submission:
          type: array
          items:
            $ref: '#/components/schemas/SubmissionPeriod'
        grading_method:
          $ref: "#/components/schemas/GradingMethod"
        group:
          type: string
          example: "Chapter 1: Data Types"
        cell_timeout:
          type: integer
          example: "300"
      example:
        late_submission:
          - period: "P1W1D"
            scaling: 0.5
          - period: "P2W1D"
            scaling: 0.2
    Submission:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int64"
        submitted_at:
          type: "string"
          format: "date-time"
          example: "2023-07-21T11:53:07Z"
        auto_status:
          $ref: "#/components/schemas/AutoStatus"
        manual_status:
          $ref: "#/components/schemas/ManualStatus"
        user_id:
          type: "integer"
          format: "int64"
        user_display_name:
          type: string
        grading_score:
          type: number
          format: float
        score_scaling:
          type: number
          format: float
          minimum: 0.0
          maximum: 1.0
        score:
          type: number
          format: float
        assignid:
          type: "integer"
          format: "int64"
        commit_hash:
          type: string
        feedback_status:
          $ref: "#/components/schemas/FeedbackStatus"
        edited:
          type: boolean
      example:
        id: 2
        submitted_at: "2023-07-21T11:53:07Z"
        auto_status: "automatically_graded"
        manual_status: "manually_graded"
        user_id: 1
        user_display_name: "emmy-noether"
        grading_score: 10.0
        score_scaling: 1
        score: 10.0
        assignid: 2
        commit_hash: "d2c2372811f226f61f106e5c3d42e5892fd25ee8"
        feedback_status: "generated"
        edited: false
    SubmissionListItemDto:
      type: object
      required: [ "id", "grading_score", "score", "feedback_status" ]
      properties:
        id:
          type: integer
          format: int64
        auto_status:
          $ref: "#/components/schemas/AutoStatus"
        manual_status:
          $ref: "#/components/schemas/ManualStatus"
        feedback_status:
          $ref: "#/components/schemas/FeedbackStatus"
        user_id:
          type: integer
          format: int64
        user_display_name:
          type: string
        grading_score:
          type: number
          format: float
        score:
          type: number
          format: float
        submitted_at:
          type: string
          format: date-time
        commit_hash:
          type: string
    SubmissionDetailInstructorDto:
      allOf:
        - $ref: "#/components/schemas/SubmissionListItemDto"
        - type: object
          required: [ "score_scaling", "edited", "extra_credit" ]
          properties:
            score_scaling:
              type: number
              format: float
              minimum: 0.0
              maximum: 1.0
            edited:
              type: boolean
            extra_credit:
              type: number
              format: float
    SubmissionPeriod:
      type: object
      properties:
        period:
          type: string
        scaling:
          type: number
          format: float
      example:
        period: "P1W1D"
        scaling: 0.5
    UserSubmissions:
      type: array
      items:
        type: object
        required: ["user", "submissions"]
        properties:
          user:
            $ref: "#/components/schemas/User"
          submissions:
            type: array
            items:
              $ref: "#/components/schemas/SubmissionListItemDto"
    RemoteFileStatus:
      type: object
      required: ["status"]
      properties:
        status:
          type: string
          enum: ["UP_TO_DATE", "DIVERGENT", "UPDATE_NEEDED", "UNSAVED_CHANGES", "NO_BACKUP"]
    AutoStatus:
      type: string
      enum: [ "not_graded", "pending", "automatically_graded", "grading_failed" ]
    ManualStatus:
      type: string
      enum: [ "not_graded", "manually_graded", "being_edited" ]
    FeedbackStatus:
      type: string
      enum: [ "not_generated", "generating", "generated", "generation_failed", "feedback_outdated" ]
    AssignmentStatus:
      type: string
      enum: [ "created", "saved", "released", "complete" ]
    GradingMethod:
      type: string
      enum: [ "auto", "full_auto", "manual"]
      default: "auto"
